/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;

/**
 *
 * @author User
 */
public class LoginRegister extends javax.swing.JFrame {

    /**
     * Creates new form LoginRegister
     */
    public LoginRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLoginUsername = new javax.swing.JTextField();
        txtLoginPass = new javax.swing.JPasswordField();
        btnCreate = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        Register = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jPasswordField4 = new javax.swing.JPasswordField();
        haveAccount = new javax.swing.JLabel();
        btnRegCreate = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        background2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("HELLO");
        Login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/password.png"))); // NOI18N
        Login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/username.png"))); // NOI18N
        Login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        txtLoginUsername.setBackground(new java.awt.Color(0, 0, 0, 50));
        txtLoginUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLoginUsername.setForeground(new java.awt.Color(204, 255, 255));
        Login.add(txtLoginUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 170, -1));

        txtLoginPass.setBackground(new java.awt.Color(0, 0, 0, 50));
        txtLoginPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLoginPass.setForeground(new java.awt.Color(204, 255, 255));
        txtLoginPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLoginPassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtLoginPassMouseEntered(evt);
            }
        });
        Login.add(txtLoginPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 170, -1));

        btnCreate.setBackground(new java.awt.Color(153, 153, 153));
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreateMouseExited(evt);
            }
        });

        jLabel4.setText("CREATE");

        javax.swing.GroupLayout btnCreateLayout = new javax.swing.GroupLayout(btnCreate);
        btnCreate.setLayout(btnCreateLayout);
        btnCreateLayout.setHorizontalGroup(
            btnCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(btnCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnCreateLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnCreateLayout.setVerticalGroup(
            btnCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(btnCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnCreateLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Login.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 70, 30));

        btnLogin.setBackground(new java.awt.Color(153, 153, 153));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });

        jLabel5.setText("LOGIN");

        javax.swing.GroupLayout btnLoginLayout = new javax.swing.GroupLayout(btnLogin);
        btnLogin.setLayout(btnLoginLayout);
        btnLoginLayout.setHorizontalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnLoginLayout.setVerticalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Login.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 70, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("or");
        Login.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/bgLogin.jpg"))); // NOI18N
        Background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackgroundMouseEntered(evt);
            }
        });
        Login.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("REGISTER");
        Register.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("Username");
        Register.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setText("Phone");
        Register.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("Email");
        Register.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("Last Password");
        Register.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("New Password");
        Register.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        jTextField3.setBackground(new java.awt.Color(0, 0, 0, 50));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        Register.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 200, -1));

        jTextField4.setBackground(new java.awt.Color(0, 0, 0, 50));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        Register.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 200, -1));

        jTextField5.setBackground(new java.awt.Color(0, 0, 0, 50));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        Register.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 200, -1));

        jPasswordField3.setBackground(new java.awt.Color(0, 0, 0, 50));
        jPasswordField3.setForeground(new java.awt.Color(255, 255, 255));
        Register.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 200, -1));

        jPasswordField4.setBackground(new java.awt.Color(0, 0, 0, 50));
        jPasswordField4.setForeground(new java.awt.Color(255, 255, 255));
        Register.add(jPasswordField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 200, -1));

        haveAccount.setBackground(new java.awt.Color(0, 0, 0));
        haveAccount.setForeground(new java.awt.Color(153, 153, 153));
        haveAccount.setText("Do you Have Account ?");
        haveAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                haveAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                haveAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                haveAccountMouseExited(evt);
            }
        });
        Register.add(haveAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, 30));

        btnRegCreate.setBackground(new java.awt.Color(153, 153, 153));
        btnRegCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegCreateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegCreateMouseExited(evt);
            }
        });

        jLabel14.setText("Create");

        javax.swing.GroupLayout btnRegCreateLayout = new javax.swing.GroupLayout(btnRegCreate);
        btnRegCreate.setLayout(btnRegCreateLayout);
        btnRegCreateLayout.setHorizontalGroup(
            btnRegCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(btnRegCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnRegCreateLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnRegCreateLayout.setVerticalGroup(
            btnRegCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(btnRegCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnRegCreateLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Register.add(btnRegCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 70, 30));

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 0, 0));
        jCheckBox1.setForeground(new java.awt.Color(204, 255, 255));
        jCheckBox1.setText("I Agree for all services");
        Register.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 200, -1));

        background2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        background2.setForeground(new java.awt.Color(204, 255, 255));
        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/bgLogin.jpg"))); // NOI18N
        Register.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Color awalLogReg = new Color(153,153,153);
    Color rubahLogReg = new Color(204,204,204);
    Color haveAcc = new Color(153,153,255);
    
    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        menu mn = new menu();
        mn.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        // TODO add your handling code here:
        btnLogin.setBackground(rubahLogReg);
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
        btnLogin.setBackground(awalLogReg);
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseClicked
        // TODO add your handling code here:
        Register.setVisible(true);
        Login.setVisible(false);
    }//GEN-LAST:event_btnCreateMouseClicked

    private void btnCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseEntered
        // TODO add your handling code here:
        btnCreate.setBackground(rubahLogReg);
    }//GEN-LAST:event_btnCreateMouseEntered

    private void btnCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseExited
        // TODO add your handling code here:
        btnCreate.setBackground(awalLogReg);
    }//GEN-LAST:event_btnCreateMouseExited

    private void BackgroundMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMouseEntered
        // TODO add your handling code here:
        btnLogin.setVisible(true);
        Register.setVisible(false);
    }//GEN-LAST:event_BackgroundMouseEntered

    private void haveAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_haveAccountMouseClicked
        // TODO add your handling code here:
        Login.setVisible(true);
        Register.setVisible(false);
    }//GEN-LAST:event_haveAccountMouseClicked

    private void haveAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_haveAccountMouseEntered
        // TODO add your handling code here:
        haveAccount.setForeground(rubahLogReg);
    }//GEN-LAST:event_haveAccountMouseEntered

    private void haveAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_haveAccountMouseExited
        // TODO add your handling code here:
        haveAccount.setForeground(awalLogReg);
    }//GEN-LAST:event_haveAccountMouseExited

    private void txtLoginPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoginPassMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginPassMouseEntered

    private void txtLoginPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoginPassMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginPassMouseClicked

    private void btnRegCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegCreateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegCreateMouseClicked

    private void btnRegCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegCreateMouseEntered
        // TODO add your handling code here:
        btnRegCreate.setBackground(rubahLogReg);
    }//GEN-LAST:event_btnRegCreateMouseEntered

    private void btnRegCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegCreateMouseExited
        // TODO add your handling code here:
        btnRegCreate.setBackground(awalLogReg);
    }//GEN-LAST:event_btnRegCreateMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Register;
    private javax.swing.JLabel background2;
    private javax.swing.JPanel btnCreate;
    private javax.swing.JPanel btnLogin;
    private javax.swing.JPanel btnRegCreate;
    private javax.swing.JLabel haveAccount;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPasswordField txtLoginPass;
    private javax.swing.JTextField txtLoginUsername;
    // End of variables declaration//GEN-END:variables
}
