/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author USER
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        bgProfil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bgprof = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtJual = new javax.swing.JLabel();
        txtCek = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTambah = new javax.swing.JLabel();
        txtHistori = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        mainVIew = new javax.swing.JPanel();
        tampilTambahData = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        tampilJualBarang = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        tampilCekStok = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField12 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        tampilHistoryPenjualan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        tampilAbout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setBackground(new java.awt.Color(34, 49, 63));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgProfil.setBackground(new java.awt.Color(52, 73, 94));
        bgProfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bgProfil.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        bgprof.setBackground(new java.awt.Color(44, 62, 80));
        bgprof.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bgprof.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, 10));
        bgprof.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 130, 10));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PROFIL");
        bgprof.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 80, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/c.png"))); // NOI18N
        bgprof.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        bgProfil.add(bgprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 190));

        txtJual.setForeground(new java.awt.Color(255, 255, 255));
        txtJual.setText("J U A L  B A R A N G");
        txtJual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtJualMouseClicked(evt);
            }
        });
        bgProfil.add(txtJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        txtCek.setForeground(new java.awt.Color(255, 255, 255));
        txtCek.setText("C E K  S T O K");
        bgProfil.add(txtCek, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("A B O U T ");
        bgProfil.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        txtTambah.setForeground(new java.awt.Color(255, 255, 255));
        txtTambah.setText(" T A M B A H   D A T A");
        txtTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTambahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtTambahMouseExited(evt);
            }
        });
        bgProfil.add(txtTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        txtHistori.setForeground(new java.awt.Color(255, 255, 255));
        txtHistori.setText("H I S T O R I   P E N J U A L A N");
        bgProfil.add(txtHistori, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jPanel4.setBackground(new java.awt.Color(44, 62, 80));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("L O G  O U T");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 20));

        bgProfil.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 210, 40));

        menu.add(bgProfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 610));

        mainVIew.setBackground(new java.awt.Color(34, 49, 63));

        javax.swing.GroupLayout mainVIewLayout = new javax.swing.GroupLayout(mainVIew);
        mainVIew.setLayout(mainVIewLayout);
        mainVIewLayout.setHorizontalGroup(
            mainVIewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        mainVIewLayout.setVerticalGroup(
            mainVIewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        menu.add(mainVIew, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 980, 610));

        tampilTambahData.setBackground(new java.awt.Color(34, 49, 63));
        tampilTambahData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("TabmahData");
        tampilTambahData.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Kode");
        tampilTambahData.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 131, -1, -1));

        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("jumlah");
        tampilTambahData.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("harga");
        tampilTambahData.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("keterangan");
        tampilTambahData.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("tipe");
        tampilTambahData.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("nama");
        tampilTambahData.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jTextField2.setText("jTextField2");
        tampilTambahData.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 150, -1));

        jTextField3.setText("jTextField2");
        tampilTambahData.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 150, -1));

        jTextField1.setText("jTextField1");
        tampilTambahData.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 150, -1));

        jTextField4.setText("jTextField4");
        tampilTambahData.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 150, -1));

        jTextField5.setText("jTextField5");
        tampilTambahData.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 150, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        tampilTambahData.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        jLabel24.setText("Tambah");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel24)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel24)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tampilTambahData.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 90, 30));

        menu.add(tampilTambahData, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 750, 610));

        tampilJualBarang.setBackground(new java.awt.Color(34, 49, 63));
        tampilJualBarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("jual");
        tampilJualBarang.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 49, -1, -1));

        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("Nama Barang");
        tampilJualBarang.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("Jumlah");
        tampilJualBarang.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("Kode");
        tampilJualBarang.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jTextField6.setText("jTextField6");
        tampilJualBarang.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 160, -1));

        jTextField7.setText("jTextField7");
        tampilJualBarang.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 160, -1));

        jTextField8.setText("jTextField8");
        tampilJualBarang.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 160, -1));

        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("Nama Pembeli");
        tampilJualBarang.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel21.setForeground(new java.awt.Color(240, 240, 240));
        jLabel21.setText("Tanggal");
        tampilJualBarang.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        jLabel22.setForeground(new java.awt.Color(240, 240, 240));
        jLabel22.setText("Tipe");
        tampilJualBarang.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        jTextField9.setText("jTextField9");
        tampilJualBarang.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 160, -1));

        jTextField10.setText("jTextField10");
        tampilJualBarang.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 160, -1));

        jTextField11.setText("jTextField11");
        tampilJualBarang.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 160, -1));

        jLabel23.setText("Jual");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel23)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel23)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tampilJualBarang.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 90, 30));

        menu.add(tampilJualBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 750, 610));

        tampilCekStok.setBackground(new java.awt.Color(34, 49, 63));
        tampilCekStok.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("CekStok");
        tampilCekStok.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 48, -1, -1));

        jLabel25.setText("Hapus");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel25)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel25)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tampilCekStok.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 90, 30));

        jLabel28.setText("Edit");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel28)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel28)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tampilCekStok.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 90, 30));

        jLabel27.setText("Cari");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel27)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel27)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tampilCekStok.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 30));

        jLabel26.setText("Sorting");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel26)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel26)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tampilCekStok.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 90, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tampilCekStok.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 170, 30));

        jTextField12.setText("jTextField12");
        tampilCekStok.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 130, 160, 30));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        tampilCekStok.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 650, 340));

        menu.add(tampilCekStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 750, 610));

        tampilHistoryPenjualan.setBackground(new java.awt.Color(34, 49, 63));

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Hisitory Penjualan");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("Tanggal\t\tNama\t\tKode\t\tBarang\t\tTipe\t\tJumlah");
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout tampilHistoryPenjualanLayout = new javax.swing.GroupLayout(tampilHistoryPenjualan);
        tampilHistoryPenjualan.setLayout(tampilHistoryPenjualanLayout);
        tampilHistoryPenjualanLayout.setHorizontalGroup(
            tampilHistoryPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilHistoryPenjualanLayout.createSequentialGroup()
                .addGroup(tampilHistoryPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tampilHistoryPenjualanLayout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jLabel4))
                    .addGroup(tampilHistoryPenjualanLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        tampilHistoryPenjualanLayout.setVerticalGroup(
            tampilHistoryPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilHistoryPenjualanLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        menu.add(tampilHistoryPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 750, 610));

        tampilAbout.setBackground(new java.awt.Color(34, 49, 63));

        jLabel7.setText("About'");

        javax.swing.GroupLayout tampilAboutLayout = new javax.swing.GroupLayout(tampilAbout);
        tampilAbout.setLayout(tampilAboutLayout);
        tampilAboutLayout.setHorizontalGroup(
            tampilAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilAboutLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel7)
                .addContainerGap(399, Short.MAX_VALUE))
        );
        tampilAboutLayout.setVerticalGroup(
            tampilAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilAboutLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel7)
                .addContainerGap(376, Short.MAX_VALUE))
        );

        menu.add(tampilAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 750, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJualMouseClicked

    }//GEN-LAST:event_txtJualMouseClicked

    private void txtTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTambahMouseClicked
        menu.removeAll();
        menu.repaint();
        menu.revalidate();

    }//GEN-LAST:event_txtTambahMouseClicked

    private void txtTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTambahMouseEntered
    // TODO add your handling code here:
    }//GEN-LAST:event_txtTambahMouseEntered

    private void txtTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTambahMouseExited

    }//GEN-LAST:event_txtTambahMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgProfil;
    private javax.swing.JPanel bgprof;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel mainVIew;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel tampilAbout;
    private javax.swing.JPanel tampilCekStok;
    private javax.swing.JPanel tampilHistoryPenjualan;
    private javax.swing.JPanel tampilJualBarang;
    private javax.swing.JPanel tampilTambahData;
    private javax.swing.JLabel txtCek;
    private javax.swing.JLabel txtHistori;
    private javax.swing.JLabel txtJual;
    private javax.swing.JLabel txtTambah;
    // End of variables declaration//GEN-END:variables
}
